# Generated by Django 5.2.5 on 2025-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='certificates',
            field=models.TextField(blank=True, help_text='List of certificates and degrees (comma-separated or JSON)'),
        ),
        migrations.AddField(
            model_name='service',
            name='degrees',
            field=models.TextField(blank=True, help_text='Educational degrees and qualifications'),
        ),
    ]
