# Generated by Django 5.2.5 on 2025-11-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_certificates_service_degrees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=180),
        ),
    ]
