# Generated by Django 5.2.5 on 2025-11-03 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service_certificates_service_degrees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_search_radius', models.PositiveIntegerField(default=50, help_text='Default search radius in kilometers')),
                ('min_price_filter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price_filter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('items_per_page', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='preferred_by_clients', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Client Preferences',
                'verbose_name_plural': 'Client Preferences',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali'), ('hi', 'Hindi')], default='en', help_text='Preferred language for the interface', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('default_location', models.CharField(blank=True, max_length=200)),
                ('preferred_currency', models.CharField(default='NPR', help_text='ISO 4217 currency code', max_length=3)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='services.service')),
            ],
            options={
                'verbose_name': 'Client Favorite',
                'verbose_name_plural': 'Client Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'service')},
            },
        ),
    ]
