# Generated by Django 5.2.5 on 2026-01-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='client_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='provider_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
