# Generated by Django 6.0.3 on 2026-04-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatthread_client_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_first_response',
            field=models.BooleanField(default=False),
        ),
    ]
