# Generated by Django 6.0.3 on 2026-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='pan',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
