# Generated by Django 5.2.5 on 2025-11-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kycverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('kyc_submitted', 'KYC Submitted'), ('booking_accepted', 'Booking Accepted'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('booking_declined', 'Booking Declined'), ('booking_requested', 'Booking Requested'), ('password_changed', 'Password Changed'), ('username_changed', 'Username Changed'), ('profile_updated', 'Profile Updated'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('service_approved', 'Service Approved'), ('service_rejected', 'Service Rejected')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_booking_id', models.IntegerField(blank=True, null=True)),
                ('related_service_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx')],
            },
        ),
    ]
