# Generated by Django 5.2.5 on 2026-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='category',
            field=models.CharField(blank=True, choices=[('flower_vendor', 'Flower Vendor'), ('event_decorator', 'Event Decorator'), ('nursery_amc', 'Nursery / Office AMC')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='trade_certificate',
            field=models.FileField(blank=True, help_text='Trade or business certificate', null=True, upload_to='kyc/certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('flower_vendor', 'Flower Vendor'), ('event_decorator', 'Event Decorator'), ('nursery_amc', 'Nursery / Office AMC')], default='flower_vendor', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
