# Generated by Django 6.0.3 on 2026-04-04 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_kycverification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBookingIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('citizenship', models.FileField(upload_to='booking_identity/citizenship/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer booking identity',
                'verbose_name_plural': 'Customer booking identities',
            },
        ),
    ]
