# Generated by Django 6.0.3 on 2026-04-04 20:58

from django.db import migrations, models


def set_phone_verified_existing(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.all().update(phone_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_booking_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Used for high-tier (Rs 5,000+) booking eligibility.'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='True after client OTP registration or manual verification; used for budget-tier bookings.'),
        ),
        migrations.RunPython(set_phone_verified_existing, migrations.RunPython.noop),
    ]
