# Generated by Django 6.0.3 on 2026-04-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_booking_tiers_and_client_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_response_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='freshness_guarantee',
            field=models.BooleanField(default=False, help_text="Provider opted in to 'fresh flowers guaranteed' badge."),
        ),
        migrations.AddField(
            model_name='user',
            name='freshness_violations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_response_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('kyc_submitted', 'KYC Submitted'), ('booking_accepted', 'Booking Accepted'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('booking_declined', 'Booking Declined'), ('booking_requested', 'Booking Requested'), ('payment_held', 'Payment Held'), ('payment_released', 'Payment Released'), ('dispute_opened', 'Dispute Opened'), ('password_changed', 'Password Changed'), ('username_changed', 'Username Changed'), ('profile_updated', 'Profile Updated'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('service_approved', 'Service Approved'), ('service_rejected', 'Service Rejected')], max_length=50),
        ),
    ]
